version: '3.9'
services:
  mariadb:
    image: mariadb:11.1.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exampledb
    volumes:
      - mariadb_volume:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mariadb_network

  tomcat:
    image: tomcat:10.1.9-jdk17
    container_name: tomcat
    ports:
      - "8090:8080"
    volumes:
      - ./assets/sample.war:/usr/local/tomcat/webapps/sample.war
    networks:
      - mariadb_network

  cloudbeaver:
    image: dbeaver/cloudbeaver:23.3.0
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    networks:
      - mariadb_network

volumes:
  mariadb_volume:
networks:
  mariadb_network: